spring.application.name=FoodHub360

spring.datasource.url=jdbc:mysql://localhost:3306/foodhub360
spring.datasource.username=useraps
spring.datasource.password=MyUser2.0

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
